// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnougmjcrsixlvgvkviv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRub3VnbWpjcnNpeGx2Z3Zrdml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzI3MDUsImV4cCI6MjA2ODE0ODcwNX0.wyqmQ0EtHI_bDUaGCIInaQJ8PXXuZAVdDcyXoXlc8DE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});